export const GET_TASKS = 'GET_TASKS'
export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const COMPLETE_TASK = 'COMPLETE_TASK'
export const GET_ACTIVE_TASKS = 'GET_ACTIVE_TASKS'
export const GET_DONE_TASKS = 'GET_DONE_TASKS'
export const CHANGE_INPUT = 'CHANGE_INPUT'
export const CLEAR_INPUT = 'CLEAR_INPUT'
